export const OTON_BARANGAYS = [
  "Abilay Norte",
  "Abilay Sur",
  "Alegre",
  "Batuan Ilaud",
  "Batuan Ilaya",
  "Bita Norte",
  "Bita Sur",
  "Botong",
  "Buray",
  "Cabanbanan",
  "Cabolo-an Norte",
  "Cabolo-an Sur",
  "Cadinglian",
  "Cagbang",
  "Calam-isan",
  "Galang",
  "Lambuyao",
  "Mambog",
  "Pakiad",
  "Poblacion East",
  "Poblacion North",
  "Poblacion South",
  "Poblacion West",
  "Pulo Maestra Vita",
  "Rizal",
  "Salngan",
  "Sambaludan",
  "San Antonio",
  "San Nicolas",
  "Santa Clara",
  "Santa Monica",
  "Santa Rita",
  "Tagbac Norte",
  "Tagbac Sur",
  "Trapiche",
  "Tuburan",
  "Turog-Turog"
];
