export const OTON_BARANGAYS = [
  "Abilay Norte",
  "Abilay Sur",
  "Alegre",
  "Batuan Ilaud",
  "Batuan Ilaya",
  "Bita Norte",
  "Bita Sur",
  "Botong",
  "Buray",
  "Cabanbanan",
  "Cabolo-an Norte",
  "Cabolo-an Sur",
  "Cadinglian",
  "Cagbang",
  "Calam-isan",
  "Galang",
  "Lambuyao",
  "Mambog",
  "Pakiad",
  "Poblacion East",
  "Poblacion North",
  "Poblacion South",
  "Poblacion West",
  "Pulo Maestra Vita",
  "Rizal",
  "Salngan",
  "Sambaludan",
  "San Antonio",
  "San Nicolas",
  "Santa Clara",
  "Santa Monica",
  "Santa Rita",
  "Tagbac Norte",
  "Tagbac Sur",
  "Trapiche",
  "Tuburan",
  "Turog-Turog",
];

export const ILOILO_MUNICIPALITIES = [
  "Oton",
  "Iloilo City",
  "Tigbauan",
  "Guimbal",
  "Miagao",
  "Pavia",
  "San Miguel",
  "Santa Barbara",
  "Leganes",
];

export const MUNICIPALITY_BARANGAYS = {
  Oton: OTON_BARANGAYS,
  "Iloilo City": [
    "Jaro",
    "Molo",
    "Mandurriao",
    "La Paz",
    "Arevalo",
    "Lapuz",
    "City Proper",
  ],
  Tigbauan: [
    "Alipata",
    "Atabayan",
    "Baguingin",
    "Barosong",
    "Buyu-an",
    "Cordova Norte",
    "Cordova Sur",
    "Namocon",
    "Parara Norte",
    "Parara Sur",
    "Poblacion East",
    "Poblacion West",
  ],
  Guimbal: [
    "Anono-o",
    "Bagonbon",
    "Balantad",
    "Bongol San Vicente",
    "Cabasi",
    "Gerona-Gimeno",
    "Nanga",
    "Poblacion Aurelio",
    "Poblacion Bagumbayan",
    "Poblacion Girogona",
    "Poblacion Libertad",
  ],
  Miagao: [
    "Banuque",
    "Baybay Sur",
    "Baybay Norte",
    "Caitib",
    "Damilisan",
    "Guibongan",
    "Kirayan Norte",
    "Kirayan Sur",
    "Mambatad",
    "Poblacion Ocho",
    "Sapa",
  ],
  Pavia: [
    "Amparo",
    "Balabag",
    "Cabugao Norte",
    "Cabugao Sur",
    "Jibao-an",
    "Mali-ao",
    "Pagsanga-an",
    "Pandac",
    "Palihan",
    "Poblacion",
  ],
  "San Miguel": [
    "Consolacion",
    "Igtambo",
    "Poblacion",
    "San Jose",
    "Santa Cruz",
    "Santa Teresa",
  ],
  "Santa Barbara": [
    "Balanac",
    "Cabugao",
    "Inangayan",
    "Malawog",
    "Poblacion",
    "Tigtig",
    "Tungay",
  ],
  Leganes: [
    "Guinobatan",
    "Malandog",
    "Nabitasan",
    "Poblacion",
    "San Vicente font",
  ],
};

export const ILOILO_CITY_BARANGAYS_BY_DISTRICT = {
  Arevalo: [
    "Bonifacio",
    "Calaparan",
    "Dulonan",
    "Mohon",
    "Quezon",
    "San Jose",
    "Santa Cruz",
    "Santa Filomena",
    "Santo Domingo",
    "Santo Niño Norte",
    "Santo Niño Sur",
    "So-oc",
    "Yulo Drive",
  ],
  Lapuz: [
    "Alalasan Lapuz",
    "Don Esteban-Lapuz",
    "Jalandoni Estate-Lapuz",
    "Lapuz Norte",
    "Lapuz Sur",
    "Libertad-Lapuz",
    "Loboc-Lapuz",
    "Mansaya-Lapuz",
    "Obrero-Lapuz",
    "Progreso-Lapuz",
    "Punong-Lapuz",
    "Sinikway",
  ],
  Molo: [
    "Calumpang",
    "Cochero",
    "Compania",
    "East Baluarte",
    "East Timawa",
    "Habog-habog Salvacion",
    "Infante",
    "Kasingkasing",
    "Katilingban",
    "Molo Boulevard",
    "North Avanceña",
    "North Baluarte",
    "North Fundidor",
    "North San Jose",
    "Poblacion Molo",
    "San Antonio",
    "San Juan",
    "San Pedro",
    "South Baluarte",
    "South Fundidor",
    "South San Jose",
    "Taal",
    "Tap-oc",
    "West Habog-habog",
    "West Timawa",
  ],
  Mandurriao: [
    "Abeto Mirasol Taft South",
    "Airport",
    "Bakhaw",
    "Bolilao",
    "Buhang Taft North",
    "Calahunan",
    "Dungon",
    "Dungon A",
    "Dungon B",
    "Guzman-Jesena",
    "Hibao-an Norte",
    "Hibao-an Sur",
    "Navais",
    "Oñate de Leon",
    "PHHC Block 17",
    "PHHC Block 22 NHA",
    "Pale Benedicto Rizal",
    "San Rafael",
    "Tabucan",
  ],
  "La Paz": [
    "Aguinaldo",
    "Baldoza",
    "Bantud",
    "Banuyao",
    "Burgos-Mabini-Plaza",
    "Caingin",
    "Divinagracia",
    "Gustilo",
    "Hinactacan",
    "Ingore",
    "Laguda",
    "Lopez Jaena",
    "Lopez Jaena Norte",
    "Lopez Jaena Sur",
    "Luna",
    "Macarthur",
    "Magsaysay",
    "Magsaysay Village",
    "Nabitasan",
    "Railway",
    "Rizal",
    "San Isidro",
    "Ticud",
  ],
  Jaro: [
    "Arguelles",
    "Balabago",
    "Balantang",
    "Benedicto",
    "Bito-on",
    "Buhang",
    "Buntatala",
    "Calubihan",
    "Camilo Cabili",
    "Cubay",
    "Democracia",
    "Desamparados",
    "Dungon",
    "Fajardo",
    "Javellana",
    "Jereos",
    "Lanit",
    "Libertad, Santa Isabel",
    "Lico-an",
    "Luna",
    "M. V. Hechanova",
    "Maria Cristina",
    "Montinola",
    "Our Lady Of Fatima",
    "Our Lady Of Lourdes",
    "Quintin Salas",
    "Sambag",
    "San Isidro",
    "San Jose",
    "San Pedro",
    "San Roque",
    "San Vicente",
    "Santa Isabel",
    "Seminario",
    "Simon Ledesma",
    "Tabuc Suba",
    "Tacas",
    "Tagbac",
    "Taytay Zone II",
    "Ungka",
  ],
  "City Proper": [
    "Arsenal Aduana",
    "Baybay Tanza",
    "Bonifacio Tanza",
    "Concepcion-Montes",
    "Danao",
    "Delgado-Jalandoni-Bagumbayan",
    "Edganzon",
    "El 98 Castilla",
    "Flores",
    "General Hughes-Montes",
    "Gloria",
    "Hipodromo",
    "Inday",
    "Jalandoni-Wilson",
    "Kahirupan",
    "Katilingban",
    "Kauswagan",
    "Legaspi dela Rama",
    "Liberation",
    "Mabolo-Delgado",
    "Maria Clara",
    "Muelle Loney-Montes",
    "Nonoy",
    "Ortiz",
    "Osmeña",
    "President Roxas",
    "Rima-Rizal",
    "Rizal Estanzuela",
    "Rizal Ibarra",
    "Rizal Palapala I",
    "Rizal Palapala II",
    "Roxas Village",
    "Sampaguita",
    "San Agustin",
    "San Felix",
    "San Jose",
    "San Nicolas",
    "Santa Rosa",
    "Santo Rosario-Duran",
    "Tanza-Esperanza",
    "Timawa Tanza I",
    "Timawa Tanza II",
    "Veterans Village",
    "Villa Anita",
    "Yulo-Arroyo",
    "Zamora-Melliza",
  ],
};
